CREATE TABLE Sensor(
    id int PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name varchar(30) NOT NULL UNIQUE
);

CREATE TABLE Indication(
    id int PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    value double precision NOT NULL,
    raining boolean NOT NULL,
    indication_date_time timestamp not null,
    sensor varchar(30) references Sensor(name)
);

SELECT * FROM Indication;

drop table Indication;
drop table Sensor;